[workspace]

members = [
    "websub",
    "websub-cli",
    "functions/websub-challenge-response",
    "functions/websub-notify",
    "functions/websub-renew",
    "functions/websub-subscribe",
    "functions/websub-webhook",


]